import type { ReportAnalysis } from "./fetch-analysis";

const SEVERITY_EMOJI: Record<string, string> = {
  critical: "🔴",
  high: "🟠",
  medium: "🟡",
  low: "🔵",
  info: "⚪",
};

export function generateMarkdownReport(data: ReportAnalysis): string {
  const date = data.completedAt
    ? new Date(data.completedAt).toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      })
    : new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  const lines: string[] = [
    `# AI CTO Report: ${data.projectName}`,
    "",
    `**Generated:** ${date}  `,
    `**SaaS Score:** ${data.score}/100 — ${data.label}`,
    "",
    "---",
    "",
  ];

  if (data.summary) {
    lines.push("## Executive Summary", "", data.summary, "", "---", "");
  }

  // Module scores
  lines.push("## Module Scores", "");
  const sortedModules = [...data.modules].sort((a, b) => a.score - b.score);
  for (const mod of sortedModules) {
    const name = mod.module.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
    lines.push(`- **${name}:** ${mod.score}/100`);
  }
  lines.push("", "---", "");

  // Findings grouped by severity
  const bySeverity = new Map<string, typeof data.findings>();
  for (const sev of ["critical", "high", "medium", "low", "info"]) {
    const group = data.findings.filter((f) => f.severity === sev);
    if (group.length > 0) bySeverity.set(sev, group);
  }

  if (bySeverity.size > 0) {
    lines.push("## Findings", "");
    for (const [severity, findings] of bySeverity) {
      const emoji = SEVERITY_EMOJI[severity] ?? "";
      const label = severity.charAt(0).toUpperCase() + severity.slice(1);
      lines.push(`### ${emoji} ${label} (${findings.length})`, "");
      for (const f of findings) {
        const modName = f.module.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
        lines.push(`#### ${f.title}`);
        lines.push(`**Module:** ${modName}  `);
        if (f.filePath) lines.push(`**File:** \`${f.filePath}\`  `);
        if (f.effort) lines.push(`**Effort:** ${f.effort} · **Impact:** ${f.impact ?? "?"}`);
        if (f.description) lines.push("", f.description);
        if (f.recommendation) lines.push("", `> **Recommendation:** ${f.recommendation}`);
        lines.push("");
      }
    }
    lines.push("---", "");
  }

  lines.push(`*Report generated by [AI CTO](https://aicto.dev) · ${date}*`);

  return lines.join("\n");
}
